version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "senha1234"
      MYSQL_DATABASE: "deposito"
    ports:
      - 3306:3306
    volumes:
      - ${PWD}/.mysql:/var/lib/mysql:rw
    user: mysql
    networks:
      - pedidos-rede

  php:
    image: meu-php:8.3
    volumes:
      - ${PWD}:/var/www/html
    networks:
      - pedidos-rede
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ${PWD}/.nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}:/var/www/html
    depends_on:
      - php
    networks:
      - pedidos-rede

networks:
  pedidos-rede:
    driver: bridge